# Generated by Django 4.1.2 on 2022-10-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_court_address_alter_court_court_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=200, null=True)),
                ('article', models.CharField(max_length=200, null=True)),
                ('contents_list', models.CharField(max_length=200, null=True)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.court')),
            ],
        ),
    ]
