# Generated by Django 4.1.2 on 2022-10-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courtfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourtFiles',
            new_name='CourtFile',
        ),
    ]
