# Generated by Django 4.1.2 on 2022-10-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_courtfiles_courtfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('scan', models.FileField(null=True, upload_to='')),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.courtfile')),
            ],
        ),
    ]
