# Generated by Django 4.1.2 on 2022-10-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='scan',
            field=models.FileField(null=True, upload_to='E:\\Dev\\inz\\inzynierka\x0ciles'),
        ),
    ]
