# Generated by Django 4.1.2 on 2022-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_file_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='scan',
            field=models.FileField(null=True, upload_to='E:\\Dev\\inz\\inzynierka\\users\\cfiles'),
        ),
    ]
