# Generated by Django 4.1.2 on 2022-10-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_file_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=200, null=True)),
                ('specialisation', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('ex_title', models.CharField(max_length=200, null=True)),
                ('term', models.CharField(max_length=200, null=True)),
                ('locality', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, null=True)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expert')),
                ('scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.file')),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.courtfile')),
            ],
        ),
    ]
