# Generated by Django 4.1.2 on 2022-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_expert_expertsstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='term',
            field=models.DateField(null=True),
        ),
    ]
