# Generated by Django 4.1.2 on 2022-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_expert_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtfile',
            name='contents_list',
            field=models.FileField(null=True, upload_to='E:\\Dev\\inz\\inzynierka\\users\\cfiles\\contents'),
        ),
        migrations.AlterField(
            model_name='file',
            name='scan',
            field=models.FileField(null=True, upload_to='E:\\Dev\\inz\\inzynierka\\users\\cfiles\\files'),
        ),
    ]
