# Generated by Django 4.1.2 on 2022-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_courtfile_contents_list_alter_file_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertsstatement',
            name='scan',
            field=models.FileField(null=True, upload_to='E:\\Dev\\inz\\inzynierka\\users\\cfiles\\statements'),
        ),
    ]
