# Generated by Django 4.1.2 on 2022-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_expertsstatement_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertsstatement',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
