# Generated by Django 4.1.2 on 2022-11-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_expertsstatement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsstatement',
            name='statement_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
