# Generated by Django 4.1.2 on 2022-12-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_file_accessrequest_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertsstatement',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='E:\\Dev\\inz\\inzynierka\\users\\cfiles\\statements'),
        ),
    ]
