# Generated by Django 4.1.2 on 2022-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_expertsstatement_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
