# Generated by Django 4.1.2 on 2022-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_accessrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
